#!/usr/bin/with-contenv sh

CONFIG_FILE=/config/config.ini

# create initial config file
if [[ ! -f "$CONFIG_FILE" ]]; then
  TMP_FILE="$(mktemp)"
  cat <<EOF >"$TMP_FILE"
[General]
check_github = 0
[Advanced]
system_analytics = 0
EOF

  install -m644 -o $PUID -g $PGID "$TMP_FILE" "$CONFIG_FILE"
fi

# change chdir
cd /config

# run with limited permissions
exec s6-setuidgid $PUID:$PGID python3 /app/Tautulli.py --nofork --nolaunch --datadir=/config
