#!/usr/bin/with-contenv sh

CONFIG_FILE=/config/config.ini

# create initial config file
if [[ ! -f "$CONFIG_FILE" ]]; then
  TMP_FILE="/tmp/$0.$$.$RANDOM"
  cat <<EOF >"$TMP_FILE"
[General]
check_github = 0
[Advanced]
system_analytics = 0
EOF

  install -m644 -o $PUID -g $PGID "$TMP_FILE" "$CONFIG_FILE"
else
  # disable check_github for updates
  sed -i "/^check_github[ ]*/s/=.*/= 0/" "$CONFIG_FILE"
  # disable analytics reports
  sed -i "/^system_analytics[ ]*/s/=.*/= 0/" "$CONFIG_FILE"
fi

# change chdir
cd /config

# run with limited permissions
exec s6-setuidgid $PUID:$PGID python3 /app/Tautulli.py --nofork --nolaunch --datadir=/config
